/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
/*
 * How to set up clock using clock driver functions:
 *
 * 1. Setup clock sources.
 *
 * 2. Setup voltage for the fastest of the clock outputs
 *
 * 3. Set up wait states of the flash.
 *
 * 4. Set up all dividers.
 *
 * 5. Set up all selectors to provide selected clocks.
 */

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Clocks v8.0
processor: LPC54618J512
package_id: LPC54618J512BD208
mcu_data: ksdk2_0
processor_version: 10.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

#include "fsl_power.h"
#include "fsl_clock.h"
#include "clock_config.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
/* System clock frequency. */
extern uint32_t SystemCoreClock;

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/
void BOARD_InitBootClocks(void)
{
    BOARD_BootClockRUN();
}

/*******************************************************************************
 ********************** Configuration BOARD_BootClockRUN ***********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockRUN
called_from_default_init: true
outputs:
- {id: ADC_clock.outFreq, value: 960 kHz}
- {id: ASYNCAPB_clock.outFreq, value: 12 MHz}
- {id: AUDPLL_clock.outFreq, value: 12.288 MHz}
- {id: DMIC_clock.outFreq, value: 480 kHz}
- {id: EMC_clock.outFreq, value: 166 MHz}
- {id: FRO12M_clock.outFreq, value: 12 MHz}
- {id: FROHF_clock.outFreq, value: 96 MHz}
- {id: FXCOM0_clock.outFreq, value: 12 MHz}
- {id: FXCOM1_clock.outFreq, value: 12 MHz}
- {id: FXCOM2_clock.outFreq, value: 12 MHz}
- {id: FXCOM3_clock.outFreq, value: 12 MHz}
- {id: FXCOM4_clock.outFreq, value: 12 MHz}
- {id: FXCOM5_clock.outFreq, value: 12 MHz}
- {id: FXCOM6_clock.outFreq, value: 12.288 MHz}
- {id: FXCOM7_clock.outFreq, value: 12 MHz}
- {id: FXCOM8_clock.outFreq, value: 12 MHz}
- {id: FXCOM9_clock.outFreq, value: 12 MHz}
- {id: LCD_clock.outFreq, value: 166 MHz}
- {id: MAIN_clock.outFreq, value: 166 MHz}
- {id: Master_clock.outFreq, value: 12 MHz}
- {id: SC0_clock.outFreq, value: 41.5 MHz}
- {id: SC1_clock.outFreq, value: 166 MHz}
- {id: SCT_clock.outFreq, value: 96 MHz}
- {id: SDIO_clock.outFreq, value: 32 MHz}
- {id: SYSPLL_clock.outFreq, value: 166 MHz}
- {id: System_clock.outFreq, value: 166 MHz}
- {id: USB0_clock.outFreq, value: 48 MHz}
settings:
- {id: ASYNCAPBCLK_OUTPUT_ENDI, value: Enabled}
- {id: ASYNC_SYSCON.ASYNCAPBCLKSELA.sel, value: SYSCON.fro_12m_clk}
- {id: EMCCLKDIV_OUTPUT_ENDI, value: Enabled}
- {id: SC0_OUTPUT_ENDI, value: Enabled}
- {id: SC1_OUTPUT_ENDI, value: Enabled}
- {id: SYSCON.ADCCLKDIV.scale, value: '100'}
- {id: SYSCON.ADCCLKSEL.sel, value: SYSCON.fro_hf}
- {id: SYSCON.AHBCLKDIV.scale, value: '1', locked: true}
- {id: SYSCON.AUDPDEC.scale, value: '32', locked: true}
- {id: SYSCON.AUD_M_MULT.scale, value: '4096'}
- {id: SYSCON.AUD_N_DIV.scale, value: '125'}
- {id: SYSCON.DMICCLKDIV.scale, value: '25', locked: true}
- {id: SYSCON.DMICCLKSEL.sel, value: SYSCON.FROHFCLKDIV}
- {id: SYSCON.EMCCLKDIV.scale, value: '1', locked: true}
- {id: SYSCON.FROHFCLKDIV.scale, value: '8', locked: true}
- {id: SYSCON.FXCLKSEL0.sel, value: SYSCON.fro_12m}
- {id: SYSCON.FXCLKSEL1.sel, value: SYSCON.fro_12m}
- {id: SYSCON.FXCLKSEL2.sel, value: SYSCON.fro_12m}
- {id: SYSCON.FXCLKSEL3.sel, value: SYSCON.fro_12m}
- {id: SYSCON.FXCLKSEL4.sel, value: SYSCON.fro_12m}
- {id: SYSCON.FXCLKSEL5.sel, value: SYSCON.fro_12m}
- {id: SYSCON.FXCLKSEL6.sel, value: SYSCON.AUDPLL_BYPASS}
- {id: SYSCON.FXCLKSEL7.sel, value: SYSCON.fro_12m}
- {id: SYSCON.FXCLKSEL8.sel, value: SYSCON.fro_12m}
- {id: SYSCON.FXCLKSEL9.sel, value: SYSCON.fro_12m}
- {id: SYSCON.LCDCLKDIV.scale, value: '1', locked: true}
- {id: SYSCON.LCDCLKSEL.sel, value: SYSCON.MAINCLKSELB}
- {id: SYSCON.MAINCLKSELA.sel, value: SYSCON.fro_hf}
- {id: SYSCON.MAINCLKSELB.sel, value: SYSCON.PLL_BYPASS}
- {id: SYSCON.MCLKCLKSEL.sel, value: SYSCON.FROHFCLKDIV}
- {id: SYSCON.M_MULT.scale, value: '166', locked: true}
- {id: SYSCON.N_DIV.scale, value: '6', locked: true}
- {id: SYSCON.PDEC.scale, value: '2', locked: true}
- {id: SYSCON.SC0CLKDIV.scale, value: '4'}
- {id: SYSCON.SCTCLKSEL.sel, value: SYSCON.fro_hf}
- {id: SYSCON.SDIOCLKDIV.scale, value: '3', locked: true}
- {id: SYSCON.SDIOCLKSEL.sel, value: SYSCON.fro_hf}
- {id: SYSCON.USB0CLKDIV.scale, value: '2'}
- {id: SYSCON.USB0CLKSEL.sel, value: SYSCON.fro_hf}
- {id: SYSCON.USB1CLKSEL.sel, value: SYSCON.USBDIRECT}
- {id: SYSCON_PDRUNCFG0_PDEN_SYS_PLL_CFG, value: Power_up}
- {id: SYSCON_PDRUNCFG1_PDEN_AUD_PLL_CFG, value: Power_up}
- {id: SYSOSCCTRL_FREQRANGE, value: High}
sources:
- {id: SYSCON.LCDCLK_EXT.outFreq, value: 48 MHz}
- {id: SYSCON._clk_in.outFreq, value: 12 MHz, enabled: true}
- {id: SYSCON.fro_hf.outFreq, value: 96 MHz}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Variables for BOARD_BootClockRUN configuration
 ******************************************************************************/
/*******************************************************************************
 * Code for BOARD_BootClockRUN configuration
 ******************************************************************************/
void BOARD_BootClockRUN(void)
{
    /*!< Set up the clock sources */
    /*!< Set up FRO */
    POWER_DisablePD(kPDRUNCFG_PD_FRO_EN);                   /*!< Ensure FRO is on  */
    CLOCK_AttachClk(kFRO12M_to_MAIN_CLK);                  /*!< Switch to FRO 12MHz first to ensure we can change voltage without accidentally
                                                                being below the voltage for current speed */
    POWER_DisablePD(kPDRUNCFG_PD_SYS_OSC);          /*!< Enable System Oscillator Power */
    SYSCON->SYSOSCCTRL = ((SYSCON->SYSOSCCTRL & ~SYSCON_SYSOSCCTRL_FREQRANGE_MASK) | SYSCON_SYSOSCCTRL_FREQRANGE(1U)); /*!< Set system oscillator range */
    POWER_SetVoltageForFreq(166000000U);             /*!< Set voltage for the one of the fastest clock outputs: System clock output */
    CLOCK_SetFLASHAccessCyclesForFreq(166000000U);    /*!< Set FLASH wait states for core */

    /*!< Set up SYS PLL */
    const pll_setup_t pllSetup = {
        .pllctrl =  SYSCON_SYSPLLCTRL_SELI(23U) | SYSCON_SYSPLLCTRL_SELP(31U) | SYSCON_SYSPLLCTRL_SELR(0U),
        .pllmdec = (SYSCON_SYSPLLMDEC_MDEC(9613U)),
        .pllndec = (SYSCON_SYSPLLNDEC_NDEC(11U)),
        .pllpdec = (SYSCON_SYSPLLPDEC_PDEC(98U)),
        .pllRate = 166000000U,
        .flags =  PLL_SETUPFLAG_WAITLOCK | PLL_SETUPFLAG_POWERUP
    };
    CLOCK_AttachClk(kFRO12M_to_SYS_PLL);        /*!< Set sys pll clock source*/
    CLOCK_SetPLLFreq(&pllSetup);                 /*!< Configure PLL to the desired value */
    /*!< Set up AUDIO PLL */
    const pll_setup_t audio_pllSetup = {
        .pllctrl = SYSCON_AUDPLLCTRL_SELI(4U) | SYSCON_AUDPLLCTRL_SELP(31U) | SYSCON_AUDPLLCTRL_SELR(0U),
        .pllmdec = (SYSCON_AUDPLLMDEC_MDEC(10784U)),
        .pllndec = (SYSCON_AUDPLLNDEC_NDEC(45U)),
        .pllpdec = (SYSCON_AUDPLLPDEC_PDEC(17U)),
        .pllRate = 12288000U,
        .flags =  PLL_SETUPFLAG_WAITLOCK | PLL_SETUPFLAG_POWERUP
    };
    CLOCK_AttachClk(kFRO12M_to_AUDIO_PLL);                         /*!< Set audio pll clock source*/
    CLOCK_SetAudioPLLFreq(&audio_pllSetup);                        /*!< Configure PLL to the desired value */

    /*!< Need to make sure ROM and OTP has power(PDRUNCFG0[17,29]= 0U) 
         before calling this API since this API is implemented in ROM code */
    CLOCK_SetupFROClocking(96000000U);              /*!< Set up high frequency FRO output to selected frequency */

    /*!< Set up dividers */
    CLOCK_SetClkDiv(kCLOCK_DivAhbClk, 1U, false);                  /*!< Reset divider counter and set divider to value 1 */
    CLOCK_SetClkDiv(kCLOCK_DivAdcAsyncClk, 0U, true);                  /*!< Reset ADCCLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivAdcAsyncClk, 100U, false);                  /*!< Set ADCCLKDIV divider to value 100 */
    CLOCK_SetClkDiv(kCLOCK_DivUsb0Clk, 0U, true);                  /*!< Reset USB0CLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivUsb0Clk, 2U, false);                  /*!< Set USB0CLKDIV divider to value 2 */
    CLOCK_SetClkDiv(kCLOCK_DivDmicClk, 0U, true);                  /*!< Reset DMICCLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivDmicClk, 25U, false);                  /*!< Set DMICCLKDIV divider to value 25 */
    CLOCK_SetClkDiv(kCLOCK_DivSdioClk, 0U, true);                  /*!< Reset SDIOCLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivSdioClk, 3U, false);                  /*!< Set SDIOCLKDIV divider to value 3 */
    CLOCK_SetClkDiv(kCLOCK_DivEmcClk, 0U, true);                  /*!< Reset EMCCLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivEmcClk, 1U, false);                  /*!< Set EMCCLKDIV divider to value 1 */
    CLOCK_SetClkDiv(kCLOCK_DivSmartCard0Clk, 0U, true);                  /*!< Reset SC0CLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivSmartCard0Clk, 4U, false);                  /*!< Set SC0CLKDIV divider to value 4 */
    CLOCK_SetClkDiv(kCLOCK_DivSmartCard1Clk, 0U, true);                  /*!< Reset SC1CLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivSmartCard1Clk, 1U, false);                  /*!< Set SC1CLKDIV divider to value 1 */
    CLOCK_SetClkDiv(kCLOCK_DivSctClk, 0U, true);                  /*!< Reset SCTCLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivSctClk, 1U, false);                  /*!< Set SCTCLKDIV divider to value 1 */
    CLOCK_SetClkDiv(kCLOCK_DivLcdClk, 0U, true);                  /*!< Reset LCDCLKDIV divider counter and halt it */
    CLOCK_SetClkDiv(kCLOCK_DivLcdClk, 1U, false);                  /*!< Set LCDCLKDIV divider to value 1 */

    /*!< Set up clock selectors - Attach clocks to the peripheries */
    CLOCK_AttachClk(kSYS_PLL_to_MAIN_CLK);                    /*!< Switch MAIN_CLK to SYS_PLL */
    SYSCON->ASYNCAPBCTRL = SYSCON_ASYNCAPBCTRL_ENABLE_MASK;       /*!< Enable ASYNC APB subsystem */
    CLOCK_AttachClk(kFRO12M_to_ASYNC_APB);                  /*!< Switch ASYNC_APB to FRO12M */
    CLOCK_AttachClk(kFRO_HF_to_ADC_CLK);                    /*!< Switch ADC_CLK to FRO_HF */
    CLOCK_AttachClk(kFRO_HF_to_USB0_CLK);                    /*!< Switch USB0_CLK to FRO_HF */
    CLOCK_AttachClk(kFRO_HF_to_SDIO_CLK);                    /*!< Switch SDIO_CLK to FRO_HF */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM0);                    /*!< Switch FLEXCOMM0 to FRO12M */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM1);                    /*!< Switch FLEXCOMM1 to FRO12M */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM2);                    /*!< Switch FLEXCOMM2 to FRO12M */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM3);                    /*!< Switch FLEXCOMM3 to FRO12M */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM4);                    /*!< Switch FLEXCOMM4 to FRO12M */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM5);                    /*!< Switch FLEXCOMM5 to FRO12M */
    CLOCK_AttachClk(kAUDIO_PLL_to_FLEXCOMM6);                    /*!< Switch FLEXCOMM6 to AUDIO_PLL */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM7);                    /*!< Switch FLEXCOMM7 to FRO12M */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM8);                    /*!< Switch FLEXCOMM8 to FRO12M */
    CLOCK_AttachClk(kFRO12M_to_FLEXCOMM9);                    /*!< Switch FLEXCOMM9 to FRO12M */
    CLOCK_AttachClk(kFRO_HF_to_SCT_CLK);                    /*!< Switch SCT_CLK to FRO_HF */
#if (FSL_CLOCK_DRIVER_VERSION >= MAKE_VERSION(2, 0, 1))
    CLOCK_AttachClk(kMAIN_CLK_to_LCD_CLK);                      /*!< Switch LCD_CLK to MAIN_CLK */
#else
    CLOCK_AttachClk(kMCLK_to_LCD_CLK);                        /*!< Switch LCD_CLK to MAIN_CLK */
#endif
    SYSCON->FROHFCLKDIV = ((SYSCON->FROHFCLKDIV & ~SYSCON_FROHFCLKDIV_DIV_MASK) | SYSCON_FROHFCLKDIV_DIV(7U)); /*!< Set FROHF CLKDIV  to value 7 */
    CLOCK_AttachClk(kFRO_HF_to_MCLK);                       /*!< Switch MCLK to FRO_HF */
    CLOCK_AttachClk(kFRO_HF_DIV_to_DMIC);                 /*!< Switch DMIC to FRO_HF_DIV */
    SYSCON->MAINCLKSELA = ((SYSCON->MAINCLKSELA & ~SYSCON_MAINCLKSELA_SEL_MASK) | SYSCON_MAINCLKSELA_SEL(3U)); /*!< Switch MAINCLKSELA to FRO_HF even it is not used for MAINCLKSELB */
    /*!< Set SystemCoreClock variable. */
    SystemCoreClock = BOARD_BOOTCLOCKRUN_CORE_CLOCK;
}

